name = "Casino"
uuid = "20e68cde-66e2-4616-9517-e6d4c2a99967"
version = "0.0.1"
authors = ["Nokenz <xxnokennyxx@gmail.com>"]

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.34.13"
julia = "1.10"
